#!/bin/bash
docker build \
--no-cache \
--rm \
--tag bristleio/plexpy:build \
--build-arg BUILD_DATE=$(date --utc +"%B-%d-%Y-%H:%M:%S-UTC") \
--build-arg VERSION=$PLEXPY_VERSION \
--build-arg GIT_BRANCH='v2' \
.
